$(document).ready(function () {
    $('.parallax').parallax();
});

var contestData = {
    'contests': [{
        'name': 'Contest 1',
        'tags': ['array', 'of', 'tags', 'go', 'here'],
        'short-description': 'short description of the contest',
        'deadline': 'Deadline:',
        'location': 'Location:',
        'age-group': 'Age Group:',
        'rule': 'Rules:',
        'full-description': 'About Contest:',
        'announcement': 'Announcement Date:',
        'prize': 'Prize:',
        'sign-up': 'Sign Up:',
        'sponsors': 'Sponsors',
        'img-src': 'img ulr goes here',
        'video-src': 'VideoUrl',
    },
    //
    {
        'name': '',
        'tags': ['array', 'of', 'tags', 'go', 'here'],
        'short-description': '',
        'deadline': 'Deadline:',
        'location': 'Location:',
        'age-group': 'Age Group:',
        'rule': 'Rules:',
        'full-description': 'About Contest:',
        'announcement': 'Announcement Date:',
        'prize': 'Prize:',
        'sign-up': 'Sign Up:',
        'sponsors': 'Sponsors',
        'img-src': 'img ulr goes here',
        'video-src': 'VideoUrl',
    }, {
        'name': 'Contest 1',
        'tags': ['array', 'of', 'tags', 'go', 'here'],
        'short-description': 'short description of the contest',
        'deadline': 'Deadline:',
        'location': 'Location:',
        'age-group': 'Age Group:',
        'rule': 'Rules:',
        'full-description': 'About Contest:',
        'announcement': 'Announcement Date:',
        'prize': 'Prize:',
        'sign-up': 'Sign Up:',
        'sponsors': 'Sponsors',
        'img-src': 'img ulr goes here',
        'video-src': 'VideoUrl',
    }, {
        'name': 'Contest 1',
        'tags': ['array', 'of', 'tags', 'go', 'here'],
        'short-description': 'short description of the contest',
        'deadline': 'Deadline:',
        'location': 'Location:',
        'age-group': 'Age Group:',
        'rule': 'Rules:',
        'full-description': 'About Contest:',
        'announcement': 'Announcement Date:',
        'prize': 'Prize:',
        'sign-up': 'Sign Up:',
        'sponsors': 'Sponsors',
        'img-src': 'img ulr goes here',
        'video-src': 'VideoUrl',
    }]
}